
name: check

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Modules
        run: yarn
      - name: Run Unit Tests
        run: yarn test