name: check

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Modules
        run: yarn
      - name: Run Unit Tests
        run: yarn test --coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  e2e-test:
    name: End To End Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Modules
        run: yarn
      - name: Build
        run: yarn build
      - name: Run TestCafe
        run: yarn run testcafe ${{ matrix.browser }}:headless e2e.test.js --app 'yarn serve -l 3000 -s build'
